### ISSUE TITLE
Sokar is Able to Modify Autoscaling Group in Dry-Run Mode  

### ISSUE THREAD

**Issue by serkas** [ThomasObenaus/sokar#98]
Regardless of the dry-run parameter value, the watcher can issue draining commands and autoscaling group size reduction: 
https://github.com/ThomasObenaus/sokar/blob/f1f98ad358df7d444f226f6d4aeef2de70a77833/scaler/watchScalingObject.go#L46

Reproduction:
* Run sokar with `SK_SCA_MODE:"nomad-dc"` and `SK_DRY_RUN:"1"`
* Modify autoscaling group to have desired size more than `SK_SCALE_OBJECT_MAX`
* Observe autoscaling group modified by sokar after `SK_SCA_WATCHER_INTERVAL` time

Is it a desired behavior or is it better not to apply any changes to infrastructure if sokar is in dry-run?

**Comment by ThomasObenaus** [comment]
Indeed this sounds like a bug from my perspective.
The intended behaviour is that, in dry-run mode, sokar just provides an indicator that a scaling was/ is needed (due to the current scaling and the incoming scaling alerts) and does no adjustments automatically. The adjustment then has to be done manually by using the scaling-endpoints of sokar.

The same should apply also for the watcher.

**Comment by ThomasObenaus** [comment]
# Testing
* Tested with nomad v0.8.6 in [devmode](https://github.com/MatthiasScholz/cos/tree/master/examples/devmode).
* Example nomad Job was [fail-service](https://github.com/ThomasObenaus/sokar/blob/master/examples/multi-group.nomad)
